# Generated by Django 2.1.3 on 2018-11-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='"Request"',
        ),
    ]
