# Generated by Django 2.1.4 on 2018-12-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_customuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
